### ISSUE TITLE
find a name

### ISSUE THREAD

**Issue by cosunae** [C2SM/iconarray#1]
See: 
https://peps.python.org/pep-0423/

In particular see: 
https://peps.python.org/pep-0008/#package-and-module-names

It recommends rather short names and all lowercase. Underscore is discouraged, but it does not mention "-".
We should also check it is not used already, and register it right away in PyPI.

Currently is probably on the too long side.

**Comment by victoria-cherkas** [comment]
iconarray as a name is agreed, closing the issue.
