### ISSUE TITLE
open repo

### ISSUE THREAD

**Issue by cosunae** [C2SM/iconarray#2]
Installation with conda currently does not work: 

https://github.com/C2SM/ICON-data-processing/blob/c0d04ccb636625cd91d50edcde86a59f74deeb7e/env/environment.yml#L17

since the repo is not public, https protocol requires authentication. 

making the repo public will solve it

**Comment by victoria-cherkas** [comment]
Repo is now public and you can clone with https again, also updated in in environment.yml
